### ISSUE TITLE
Do not try to double template files which are used multiple times

### ISSUE THREAD

**Issue by Hosni-Abbes** [T3Voila/templavoilaplus#413] opened 2022-07-15 07:25 UTC
Issue while upgrading Templavoila Plus from v7 to v8.
Description of the issue:
First, i upgrade Typo3 from version 9 to 11
Then i want to upgrade Templavoila plus from v7 to 8.1.1
When i click the button "Start Update Scripts", then click on "Update configuration to Templavoila Plus 8", then click "Start with step 1", then "continue with step 2", then i create new extension and click "continue with step 3" ... 
But it shows this error: 
Doubled file names arent implemented yet: "C:/laragon/www/mysite/typo3conf/ext/tvplus_updated/Resources/Private/TVP/Template/index.html" 

![img](https://user-images.githubusercontent.com/71474612/179173504-e01541fb-a5c8-4fdc-a5bf-bd99c87faefa.png)

**Comment by Hosni-Abbes** [comment] 2022-07-15 09:42
No, inside the old installation i have only one file "index.html" , it is located under "fileadmin/templates"

**Comment by Hosni-Abbes** [comment] 2022-07-19 07:25
Yes

**Comment by opi99** [comment] 2022-07-22 11:16
Ok, this should need another fix then, hopefully on this weekend

**Comment by opi99** [comment] 2022-08-20 23:33
So, checked the source and this functionality is already implemented, I did it in the first implementation already.
So, something else seams wrong for the situation if more as one TObj uses the same template file. The corresponding mapping yaml file are getting same filename with an extended number at the end.
 (Check for double usage https://github.com/T3Voila/templavoilaplus/blob/f009a9c7519279846f69f2be68b6df8b56ae17ef/Classes/Controller/Backend/ControlCenter/Update/TemplaVoilaPlus8Controller.php#L1558 )

So, can someone check, whats goes wrong there?

**Comment by jpmschuler** [comment] 2022-08-30 09:28
> True, but why is this line implemented then?

These seem to be two scenarios: The one in L1558 checks for if the src was already processed, the other in L1571 checks if the destination exists.
I e.g. had different TObjs pointing to different `my/templateA/index.html` and `my/templateB/index.html` files raising a problem, thus the SRC was not processed already (check in L1558), but still the generated filename `index.html` already existed (check in L1571).

Disclaimer: However I did my last wizard run in 8.0.0-alpha2 and resolved such issues with renaming, or converting one template and copy'n'paste and adapt the results to my other templates by hand, so it is just an educated guess, not a concrete debugging.

**Comment by opi99** [comment] 2022-08-30 13:46
So back to the question:

Do you have 2 or more TemplateObjects which use the same file and we get this error (then there must a mistake in source and someone needs to debug it)
Or you are using the same filename multiple times, then it needs to be implemented, which would eliminate also issue above but not by resolving but by creating multiple files, which would not correct.

**Comment by opi99** [comment] 2022-08-30 15:55
Ok, thanks for feedback, this needs a change

Now I would like to get feedback from @Hosni-Abbes

**Comment by opi99** [comment] 2022-08-30 15:56
As he already wrote he has only one file ... I meant to get feedback if he could look deeper in the issue on his installation.

**Comment by Hosni-Abbes** [comment] 2022-09-07 13:33
@opi99 I already check all files, i have more than one TObj which use the same template file.
https://github.com/T3Voila/templavoilaplus/blob/f009a9c7519279846f69f2be68b6df8b56ae17ef/Classes/Controller/Backend/ControlCenter/Update/TemplaVoilaPlus8Controller.php#L1558
This line will check for double usage and thats okay, but the problem is in Line 1571 which it will check the first file and then it will throw an exception because the file is already exist!?

**Comment by opi99** [comment] 2022-09-22 07:48
@Hosni-Abbes Response would be nice, so I can go over to next release.

**Comment by Hosni-Abbes** [comment] 2022-09-23 12:32
@opi99 
When debug:
1- $copiedTemplateFiles: 2 files
C:/laragon/www/site/fileadmin/templates/index.html
C:/laragon/www/site/fileadmin/templates/bottom.html

2- $source: C:/laragon/www/site/fileadmin/sitename/index.html

3- $filename: index.html

4- $destination: C:/laragon/www/site/typo3conf/ext/tvplus/Resources/Private/TVP/Template/


So, the line 1559 is not true thats why it can reach line 1571..

I try when comment this line of code (1571) it complete the process.. (just for testing).

**Comment by opi99** [comment] 2022-09-23 15:42
So, it isn't caused by "using same file" as you wrote, it is caused by "using same filename".

So answer https://github.com/T3Voila/templavoilaplus/issues/413#issuecomment-1185369902 was wrong and the topic of this issue is also wrong?

**Comment by Hosni-Abbes** [comment] 2022-09-26 13:14
There are many TObj that uses the same file (same file path: fileadmin/template/index.html).
I tried to remove all other files (with same filename) and it shows the same error..

**Closed** 2022-10-21 11:05 UTC
Labels: Feature
