### ISSUE TITLE
Cut&Paste in Page module duplicates references

### ISSUE THREAD

**Issue by akiessling** [T3Voila/templavoilaplus#281] opened 2020-06-18 10:29 UTC
Scenario:
* container element with two content elements inside (1 and 2)
* cut the first (1) element with the context menu
* insert after the second one

Expected result: the element is just moved -> 2,1
Actual result: the reference list in the container element now has a duplicate: 1,2,1

This does not happen with the dedicated cut button next to the unlink button.

TV+ Version 7.3.2

![grafik](https://user-images.githubusercontent.com/2895543/85009721-32c4f700-b15f-11ea-9933-5564e35969fd.png)

**Comment by opi99** [comment] 2022-06-28 09:03
Checked this, the issue is that the TYPO3 core function don't know anything about the "position" inside the element. So the content of the clipboard only holds the tablename and uid. Using the TV+ button also adds the path information.

But old TemplaVoila uses this path information for the move operation if it is not present, only linking will be done and so we have a new reference.

TV+ v8 will search for this missing path information and will do this moving, I won't fix this in the v7 line, as this may result in changed handling.

**Closed by opi99** 2022-06-28 09:03 UTC
